# Generated by Django 5.2.7 on 2025-10-14 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(max_length=200)),
                ('tipo_evento', models.CharField(choices=[('boda', 'Boda'), ('quinse', 'Quince Años'), ('cumple', 'Cumpleaños'), ('otro', 'Otro')], max_length=50)),
                ('password_vip', models.CharField(max_length=100)),
                ('banner', models.CharField(choices=[('banner1', 'Banner 1'), ('banner2', 'Banner 2'), ('banner3', 'Banner 3')], max_length=100)),
                ('sonido_dj', models.CharField(choices=[('dj1', 'Sonido DJ 1'), ('dj2', 'Sonido DJ 2'), ('dj3', 'Sonido DJ 3')], max_length=100)),
                ('fecha_inicio_evento', models.DateTimeField()),
                ('fecha_fin_evento', models.DateTimeField()),
                ('cooldown', models.FloatField(help_text='Tiempo en minutos para enviar nuevo mensaje')),
                ('estado', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('saludo', 'Saludo'), ('cancion', 'Canción')], max_length=50)),
                ('mensaje', models.TextField()),
                ('vip', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='eventos.evento')),
            ],
        ),
    ]
