# Generated by Django 5.2.7 on 2025-10-15 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SonidoDJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('eslogan', models.TextField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=50, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('tiktok', models.URLField(blank=True, null=True)),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='sonidos/')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='sonidos/')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='evento',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='eventos.banner'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='sonido_dj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='eventos.sonidodj'),
        ),
    ]
