# Generated by Django 5.2.7 on 2025-10-21 21:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_banner_sonidodj_alter_evento_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='cliente_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo_evento',
            field=models.CharField(choices=[('boda', 'Boda'), ('quinse', 'Quince Años'), ('cumple', 'Cumpleaños'), ('fiesta', 'Fiesta'), ('otro', 'Otro')], max_length=50),
        ),
    ]
