# Generated by Django 5.2.7 on 2025-10-21 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_mensaje_cliente_id_mensaje_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='cliente_id',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='created_at',
        ),
    ]
