# Generated by Django 5.2.7 on 2025-10-21 21:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_remove_mensaje_cliente_id_remove_mensaje_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
